### PR TITLE
Linux Port

### PR DESCRIPTION
**Pull request by Nihlus**
I've gone ahead and ported the build setup to Linux. The game now runs and works on Debian and Debian derivations. I've not been able to test the game very extensively, but it's stable as far as I've seen.

Summary of changes:
- Added a CMake build path for the game
- Added a setup script for Debian-based linux distributions
- Updated README.md, providing a link to the base CMake project and detailing some build instructions for Linux

Tested with OpenFrameworks 0.9.3, Linux Mint 18 and CLion 2016.2.

### CODE REVIEW

**Comment by andymasteroffish** [comment]
Hi there! What a nice treat to see this in my inbox! I'm super busy this weekend, but will go over this as soon as I can!

Do you have a linux build I could send to some folks to try out since I do not have a linux box to build on? You can send it to andy@andymakes.com.

Also, would you be comfortable with me adding the linux port to the game's itch.io page (https://andymakes.itch.io/intimate-codex)? If so, please let me know how you would like to be credited!

Thanks for doing this!

**Comment by andymasteroffish** [comment]
Likewise, I would want to credit you in the about_and_credits.txt file that I distribute with the app.

**Comment by Nihlus** [comment]
I'd be very happy for a Linux build to be added to the Itch.io page! Getting more Linux games out there is great :D

I've sent you a compiled build. It's a bit of a handyman's build, since it's distro agnostic and doesn't have any automatic dependency installation. I'll see about putting together a debian package for it.

If you want to add me to the credits, go ahead :) If possible, add my email as a contact as I do game porting for free at the moment. I'm always looking for new projects that interest me.

**Comment by Powersource** [comment]
*cough*

**Comment by Lyonard** [comment]
Ahem.. merge? :D

**Comment by andymasteroffish** [comment]
Hi, I don't have a linux box myself, but I've had a handful of friends try it who all had issues running it. I'm looking for somebody else to give it a whirl before merging. If either of you have tried it successfully, let me know!

**Comment by andymasteroffish** [comment]
Hey, this is way way late, but I finally setup a Linux VM and tested this thing out. It worked, so I'm finally merging this.

Sorry for the ridiculous delay. Thank you for making this port.

**Comment by Nihlus** [comment]
Talk about timing - I was just going through my notifications :P 

Happy to have helped!

**Pull request merged**
